version: 2
jobs:
  build:
    docker:
      - image: python:3.7-alpine3.8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install node and npm
          command: |
            apk add --update nodejs nodejs-npm

      - run:
          name: install serverless and plugins
          command: |
            sudo npm install -g serverless
            npm install --save serverless-pseudo-parameters
            npm install --save serverless-appsync-plugin

      - run:
          name: configure aws
          command: |
            aws configure set aws_access_key_id ACCESS_KEY
            aws configure set aws_secret_access_key SECRET_KEY
            aws configure set region us-east-1

      - run:
          name: deploy
          command: |
            serverless deploy -s dev